### ISSUE TITLE
xcodebuild Warning: Conflicting class XCBuildConfiguration

### ISSUE THREAD

**Issue by NoxHarmonium** [lucholaf/Auto-Importer-for-Xcode#10]
When I use xcodebuild I get the following warning:

*objc[30712]: Class XCBuildConfiguration is implemented in both /Applications/Xcode6.1.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore and /Users/seandawson/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.*

There may be a conflicting class in this project that needs to be renamed or not included in the final package.

**Comment by johnboiles** [comment]
This is an annoyance. I think it can be fixed by just renaming the `XCBuildConfiguration` class in this project. Here's another project with a similar issue

https://github.com/markohlebar/Peckham/issues/27

**Comment by lucholaf** [comment]
This is an issue from this dependency: https://github.com/jasperblues/XcodeEditor, can't simple rename the class in the auto-importer project.

**Comment by johnboiles** [comment]
Ah, I see. Opened the issue there:
https://github.com/jasperblues/XcodeEditor/issues/44

**Comment by lucholaf** [comment]
closing since it's not a warning from this project but from one of the dependencies.

**Comment by lucholaf** [comment]
@johnboiles awesome thanks, project updated now.

**Comment by jasperblues** [comment]
Sorry for the delay: I saw the Peckham issue a while back, but the comments suggested a pull request was forthcoming so I didn't log it. 

@NoxHarmonium, I would appreciate if your Readme notes that Auto-Importer uses the XcodeEditor library, as you've done with Peckham :+1:

**Comment by lucholaf** [comment]
@jasperblues :+1:
