### ISSUE TITLE
Failed to load nib in xcode 6.3 

### ISSUE THREAD

**Issue by remzr7** [lucholaf/Auto-Importer-for-Xcode#14]

**Comment by lucholaf** [comment]
@remzr7 please delete ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/ and ~/library/Developer/Xcode/DerivedData/* and re-install

**Comment by gerald-coddut** [comment]
Sadly, this did not help me. Any other options?

**Comment by lucholaf** [comment]
@gerald-coddut glad to hear, will see if I can add your notes to the README since I have no hint why this happen from time to time.

**Comment by gerald-coddut** [comment]
Sure, glad to help!
