### ISSUE TITLE
Auto importer does no longer work in newest Xcode version

### ISSUE THREAD

**Issue by FramusRock** [lucholaf/Auto-Importer-for-Xcode#16]
Does anyone else have this issue?

**Comment by river2202** [comment]
I have same issue and can't make it work with Version 6.3.2 (6D2105). Peckham can work partly.

**Comment by FramusRock** [comment]
I once got it to work by including the new DVTPlugInCompatibilityUUID by hand. (I found it somewhere else on GitHub). But unfotunately, I doesn't work now any longer.

I think it's pretty annoying that all Xcode plugins stop working after any update.

**Comment by river2202** [comment]
Just found a pull request from @zenangst to fix this problem. His fix work perfectly. @lucholaf, you should merge the pull request from @zenangst. Also found FuzzyAutocompletePlugin has fixed the compatible issue for Xcode 6.3.2.
https://github.com/FuzzyAutocomplete/FuzzyAutocompletePlugin/commit/2e390ab9440a9a97567501f4bbb3d363abc10bec

**Comment by lucholaf** [comment]
merged

**Comment by zenangst** [comment]
:beers:
