### ISSUE TITLE
crash on OS X 10.10.2 

### ISSUE THREAD

**Issue by lisi1987** [lucholaf/Auto-Importer-for-Xcode#7]
Clicked `ctr+cmd+H`  the xcode(6.1) crash on  OS X 10.10.2

**Comment by lucholaf** [comment]
could you please send the crash log or try with this: https://github.com/lucholaf/Auto-Importer-for-Xcode/issues/3#issuecomment-61794799

**Comment by lucholaf** [comment]
@lisi1987 try with the above solution and tell me if that works.

**Comment by lucholaf** [comment]
fixed on 3fe15120bebaf11693eec1f1787df47fd2437fc1
